require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'config/initializers/**/*'
    - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: true